name: main

on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: set tag
        run: |
          echo "full_tag=$(grep ARG Dockerfile | sed 's/ARG v=//')" >> ${GITHUB_ENV}
          echo "tag=$(grep ARG Dockerfile | sed 's/ARG v=//' | cut -d '.' -f -2)" >> ${GITHUB_ENV}
      - name: build
        run: docker build -t crs4/cmake:${{ env.full_tag }} -t crs4/cmake:${{ env.tag }} .
      - name: login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
      - name: push
        run: |
          for t in ${{env.full_tag}} ${{env.tag}}; do
            docker push crs4/cmake:${t}
          done
