name: main

on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: set tag
        run: echo "tag=$(grep ARG Dockerfile | sed 's/ARG v=//')" >> ${GITHUB_ENV}
      - name: build
        run: docker build -t crs4/cmake:${{ env.tag }} .
      - name: login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
      - name: push
        run: docker push crs4/cmake:${{ env.tag }}
